# Generated by Django 2.0.2 on 2018-04-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditability', models.IntegerField()),
                ('account_balance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('previous_credit_payment_status', models.IntegerField()),
                ('purpose', models.IntegerField()),
                ('credit_amount', models.IntegerField()),
                ('value_savings', models.IntegerField()),
                ('len_of_cur_employement', models.IntegerField()),
                ('installment_percent', models.IntegerField()),
                ('sex_marital_status', models.IntegerField()),
                ('guarantors', models.IntegerField()),
                ('duration_cur_addr', models.IntegerField()),
                ('most_valuable_asset', models.IntegerField()),
                ('age', models.IntegerField()),
                ('concurrent_credits', models.IntegerField()),
                ('type_of_appt', models.IntegerField()),
                ('credit_this_bank', models.IntegerField()),
                ('occupation', models.IntegerField()),
                ('no_of_dependents', models.IntegerField()),
                ('tel_no', models.IntegerField()),
                ('foreign_worker', models.IntegerField()),
            ],
        ),
    ]
